### ISSUE TITLE
Missing previous hash

### ISSUE THREAD

**Issue by mschristensen** [crisadamo/gochain#3]
Looks like you're not supplying the previous hash when mining?

https://github.com/crisadamo/gochain/blob/fc3aa97147b0634d043c56db4ef6900ee3116cce/handler.go#L100

Awesome work - this is a really useful resource!

**Comment by crisadamo** [comment]
Hi Mike, thanks for your interest in the project! Super cool that someone finds it useful!
Regarding your comment, the last hash is added automatically when calling the `NewBlock` with the second parameter empty. You can look at here https://github.com/crisadamo/gochain/blob/fc3aa97147b0634d043c56db4ef6900ee3116cce/blockchain.go#L62

Let me know if that makes sense.
PS: Sorry for the late answer. For some reason, I couldn't make that github send me the notifications.
