### ISSUE TITLE
Package issue?

### ISSUE THREAD

**Issue by agentbond007** [crisadamo/gochain#4]
Hi Cristian, 
I get the following error when I build. 
Thank you for clue. 

gochain/cmd(master*) » go build -o gobuild                                                                                        
main.go:6:5: cannot find package "github.com/crisadamo/gochain" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/crisadamo/gochain (from $GOROOT)
	/Users/eos/go/src/github.com/crisadamo/gochain (from $GOPATH)

**Comment by crisadamo** [comment]
Hi Bond! (This sounds super cool haha)
It seems that you do not have configured well the $GOPATH could it be?

Let me know if it works or not.
PS: Sorry for the late answer.

**Comment by agentbond007** [comment]
during build
in main.go  looking for package during import 
"github.com/crisadamo/gochain"

**Comment by agentbond007** [comment]
Got it working.
Need to use 
go get github.com/crisadamo/gochain
then 
go build -o gochain

**Comment by crisadamo** [comment]
Awesome! let me know if you need help with something else 🤙
