### ISSUE TITLE
Hashing of blocks is not working

### ISSUE THREAD

**Issue by Grrrben** [crisadamo/gochain#5]
Hi,

Nice project. Was working on a Go Blockchain implementation myself and noticed that your hashing always returns the same hash, throughout the entire chain.

The thing is that you are trying to hash a block with ` binary.Write(&buf, binary.BigEndian, block)` which gives you an error you don't handle. The data for `binary.Write` must be a fixed-size value, your Block contains a string which isn't fixed size.

I've made a workaround by marshalling the block first, that way the `binary.Write` succeeds and your hashing the chain properly. It is a bit slow though, if you'll find a better solution, drop me a line.

You can see it here, feel free to use it:
https://github.com/Grrrben/gocoin/blob/master/blockchain.go#L55

Cheers.

**Comment by phrozen** [comment]
From the article at:
https://hackernoon.com/learn-blockchains-by-building-one-117428612f46

`block_string = json.dumps(block, sort_keys=True).encode()`

Shouldn't the block be JSON encoded before hashing? that is the only way to make sure other services/clients can check the hashes if they are not implemented in Go as we actually send the chain data in JSON format.

**Comment by Grrrben** [comment]
Althought it might not be the most efficient way of hashing the blocks, your viewpoint of using json in order to be able supporting multiple languages is an interesting one. It's an easy fix, see PR https://github.com/crisadamo/gochain/pull/6. @crisadamo would you be so kind to review and/or merge?

**Comment by crisadamo** [comment]
Hi @Grrrben sure! it seems ok, I'll merge it.
